StylesPath = .github/styles
MinAlertLevel = suggestion

Packages = Google, Microsoft
Vocab = Doc

[*.md]
BasedOnStyles = Vale, Microsoft
# --- CUSTOMIZATIONS ---
Microsoft.Contractions = NO
Microsoft.Foreign = NO
Microsoft.Plurals = NO
Microsoft.Dashes = NO
Vale.Terms = NO