site_name: Splash Admin Panel
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Accessing Customer Data: customer-data.md
  - Creating Portals: creating-portals.md
  - Integrations:
      - Ubiquiti Unifi: integrations/unifi.md
theme:
  name: material
  logo: assets/logo.png
  palette:
    - scheme: default
      primary: blue  # Change primary color
      accent: amber   # Change accent color
  features:
    - navigation.expand  # Ensures the Integrations section stays open
extra:
  generator: false
  favicon: assets/images/favicon.png
  homepage: https://docs.splashnetworks.co
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@splashnetworksco
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/splash-networks/