site_name: Splash Air Docs
site_description: Documentation for Splash Air
site_url: https://docs.splashnetworks.co
site_author: Splash Networks
copyright: Copyright &copy; 2025 Splash Networks

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Defining Templates: defining-templates.md
  - Creating Portals:
      - portals/index.md
      - Aruba/HPE Instant On: portals/aruba-instant-on.md
      - Cambium: portals/cambium.md
      - Cisco: portals/cisco.md
      - Coova Chilli: portals/coova-chilli.md
      - Draytek: portals/draytek.md
      - Fortinet: portals/fortinet.md
      - LigoWave: portals/ligowave.md
      - Mikrotik: portals/mikrotik.md
      - Mikrotik with RADIUS: portals/mikrotik-with-radius.md
      - Open Mesh: portals/openmesh.md
      - OpenNDS: portals/opennds.md
      - Ruckus One: portals/ruckusone.md
      - Ruckus SmartZone: portals/ruckus-smartzone.md
      - Ruijie: portals/ruijie.md
      - TP-Link Omada: portals/omada.md
      - Ubiquiti Unifi: portals/unifi.md
  - Accessing Customer Data:
      - customer-data/index.md
      - Through Web: customer-data/web.md
      - Through API: customer-data/api.md
theme:
  name: material
  logo: assets/logo.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - navigation.expand
    - header.autohide
    - navigation.footer
    - navigation.path
    - navigation.indexes
    - navigation.top
plugins:
  - glightbox
  - search
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  generator: false
  favicon: assets/images/favicon.png
  homepage: https://docs.splashnetworks.co
  social:
    - icon: fontawesome/solid/globe
      link: https://splashnetworks.co
    - icon: fontawesome/solid/paper-plane
      link: mailto:hello@splashnetworks.co
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@splashnetworksco
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/splash-networks/
    - icon: fontawesome/brands/github
      link: https://github.com/splash-networks
  analytics:
    provider: google
    property: G-1ZJ93Z9D5T
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
