site_name: Splash Admin Panel
site_url: https://docs.splashnetworks.co
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Defining Templates: defining-templates.md
  - Creating Portals:
      - portals/index.md
      - Ubiquiti Unifi: portals/unifi.md
      - Aruba/HPE Instant On: portals/aruba-instant-on.md
  - Accessing Customer Data:
      - customer-data/index.md
      - Through Web: customer-data/web.md
      - Through API: customer-data/api.md
theme:
  name: material
  logo: assets/logo.png
  palette:
    - scheme: default
      primary: blue  # Change primary color
      accent: amber   # Change accent color
  features:
    - navigation.expand
    - header.autohide
    - navigation.footer
    - navigation.path
    - navigation.indexes
    - navigation.top
plugins:
  - glightbox
  - search
extra:
  generator: false
  favicon: assets/images/favicon.png
  homepage: https://docs.splashnetworks.co
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:hello@splashnetworks.co
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@splashnetworksco
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/splash-networks/
  metadata:
    title: "Splash Networks Docs"
    description: "Documentation for Splash Admin"
    image: "https://docs.splashnetworks.co/assets/logo.png"
    og:image: "https://docs.splashnetworks.co/assets/logo.png"
    og:type: "website"
    og:url: "https://docs.splashnetworks.co/"
    og:title: "Splash Networks Docs"
    og:description: "Official documentation for Splash Networks"
  analytics:
    provider: google
    property: G-1ZJ93Z9D5T
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
